# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/cuntainer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/cuntainer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/cuntainer/CMakeFiles /root/cuntainer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/cuntainer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cutils

# Build rule for target.
cutils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cutils
.PHONY : cutils

# fast build rule for target.
cutils/fast:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/build
.PHONY : cutils/fast

#=============================================================================
# Target rules for targets named linkRecursive

# Build rule for target.
linkRecursive: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linkRecursive
.PHONY : linkRecursive

# fast build rule for target.
linkRecursive/fast:
	$(MAKE) -f CMakeFiles/linkRecursive.dir/build.make CMakeFiles/linkRecursive.dir/build
.PHONY : linkRecursive/fast

#=============================================================================
# Target rules for targets named mounts

# Build rule for target.
mounts: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mounts
.PHONY : mounts

# fast build rule for target.
mounts/fast:
	$(MAKE) -f CMakeFiles/mounts.dir/build.make CMakeFiles/mounts.dir/build
.PHONY : mounts/fast

#=============================================================================
# Target rules for targets named nsswitcher

# Build rule for target.
nsswitcher: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 nsswitcher
.PHONY : nsswitcher

# fast build rule for target.
nsswitcher/fast:
	$(MAKE) -f CMakeFiles/nsswitcher.dir/build.make CMakeFiles/nsswitcher.dir/build
.PHONY : nsswitcher/fast

#=============================================================================
# Target rules for targets named prepareEnvDir

# Build rule for target.
prepareEnvDir: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 prepareEnvDir
.PHONY : prepareEnvDir

# fast build rule for target.
prepareEnvDir/fast:
	$(MAKE) -f CMakeFiles/prepareEnvDir.dir/build.make CMakeFiles/prepareEnvDir.dir/build
.PHONY : prepareEnvDir/fast

src/linkRecursive.o: src/linkRecursive.c.o
.PHONY : src/linkRecursive.o

# target to build an object file
src/linkRecursive.c.o:
	$(MAKE) -f CMakeFiles/linkRecursive.dir/build.make CMakeFiles/linkRecursive.dir/src/linkRecursive.c.o
.PHONY : src/linkRecursive.c.o

src/linkRecursive.i: src/linkRecursive.c.i
.PHONY : src/linkRecursive.i

# target to preprocess a source file
src/linkRecursive.c.i:
	$(MAKE) -f CMakeFiles/linkRecursive.dir/build.make CMakeFiles/linkRecursive.dir/src/linkRecursive.c.i
.PHONY : src/linkRecursive.c.i

src/linkRecursive.s: src/linkRecursive.c.s
.PHONY : src/linkRecursive.s

# target to generate assembly for a file
src/linkRecursive.c.s:
	$(MAKE) -f CMakeFiles/linkRecursive.dir/build.make CMakeFiles/linkRecursive.dir/src/linkRecursive.c.s
.PHONY : src/linkRecursive.c.s

src/mounts.o: src/mounts.c.o
.PHONY : src/mounts.o

# target to build an object file
src/mounts.c.o:
	$(MAKE) -f CMakeFiles/mounts.dir/build.make CMakeFiles/mounts.dir/src/mounts.c.o
.PHONY : src/mounts.c.o

src/mounts.i: src/mounts.c.i
.PHONY : src/mounts.i

# target to preprocess a source file
src/mounts.c.i:
	$(MAKE) -f CMakeFiles/mounts.dir/build.make CMakeFiles/mounts.dir/src/mounts.c.i
.PHONY : src/mounts.c.i

src/mounts.s: src/mounts.c.s
.PHONY : src/mounts.s

# target to generate assembly for a file
src/mounts.c.s:
	$(MAKE) -f CMakeFiles/mounts.dir/build.make CMakeFiles/mounts.dir/src/mounts.c.s
.PHONY : src/mounts.c.s

src/nsswitcher.o: src/nsswitcher.c.o
.PHONY : src/nsswitcher.o

# target to build an object file
src/nsswitcher.c.o:
	$(MAKE) -f CMakeFiles/nsswitcher.dir/build.make CMakeFiles/nsswitcher.dir/src/nsswitcher.c.o
.PHONY : src/nsswitcher.c.o

src/nsswitcher.i: src/nsswitcher.c.i
.PHONY : src/nsswitcher.i

# target to preprocess a source file
src/nsswitcher.c.i:
	$(MAKE) -f CMakeFiles/nsswitcher.dir/build.make CMakeFiles/nsswitcher.dir/src/nsswitcher.c.i
.PHONY : src/nsswitcher.c.i

src/nsswitcher.s: src/nsswitcher.c.s
.PHONY : src/nsswitcher.s

# target to generate assembly for a file
src/nsswitcher.c.s:
	$(MAKE) -f CMakeFiles/nsswitcher.dir/build.make CMakeFiles/nsswitcher.dir/src/nsswitcher.c.s
.PHONY : src/nsswitcher.c.s

src/prepareEnvDir.o: src/prepareEnvDir.c.o
.PHONY : src/prepareEnvDir.o

# target to build an object file
src/prepareEnvDir.c.o:
	$(MAKE) -f CMakeFiles/prepareEnvDir.dir/build.make CMakeFiles/prepareEnvDir.dir/src/prepareEnvDir.c.o
.PHONY : src/prepareEnvDir.c.o

src/prepareEnvDir.i: src/prepareEnvDir.c.i
.PHONY : src/prepareEnvDir.i

# target to preprocess a source file
src/prepareEnvDir.c.i:
	$(MAKE) -f CMakeFiles/prepareEnvDir.dir/build.make CMakeFiles/prepareEnvDir.dir/src/prepareEnvDir.c.i
.PHONY : src/prepareEnvDir.c.i

src/prepareEnvDir.s: src/prepareEnvDir.c.s
.PHONY : src/prepareEnvDir.s

# target to generate assembly for a file
src/prepareEnvDir.c.s:
	$(MAKE) -f CMakeFiles/prepareEnvDir.dir/build.make CMakeFiles/prepareEnvDir.dir/src/prepareEnvDir.c.s
.PHONY : src/prepareEnvDir.c.s

src/utils.o: src/utils.c.o
.PHONY : src/utils.o

# target to build an object file
src/utils.c.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/src/utils.c.o
	$(MAKE) -f CMakeFiles/mounts.dir/build.make CMakeFiles/mounts.dir/src/utils.c.o
.PHONY : src/utils.c.o

src/utils.i: src/utils.c.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.c.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/src/utils.c.i
	$(MAKE) -f CMakeFiles/mounts.dir/build.make CMakeFiles/mounts.dir/src/utils.c.i
.PHONY : src/utils.c.i

src/utils.s: src/utils.c.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.c.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/src/utils.c.s
	$(MAKE) -f CMakeFiles/mounts.dir/build.make CMakeFiles/mounts.dir/src/utils.c.s
.PHONY : src/utils.c.s

src/utilsMount.o: src/utilsMount.c.o
.PHONY : src/utilsMount.o

# target to build an object file
src/utilsMount.c.o:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/src/utilsMount.c.o
.PHONY : src/utilsMount.c.o

src/utilsMount.i: src/utilsMount.c.i
.PHONY : src/utilsMount.i

# target to preprocess a source file
src/utilsMount.c.i:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/src/utilsMount.c.i
.PHONY : src/utilsMount.c.i

src/utilsMount.s: src/utilsMount.c.s
.PHONY : src/utilsMount.s

# target to generate assembly for a file
src/utilsMount.c.s:
	$(MAKE) -f CMakeFiles/cutils.dir/build.make CMakeFiles/cutils.dir/src/utilsMount.c.s
.PHONY : src/utilsMount.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... cutils"
	@echo "... edit_cache"
	@echo "... linkRecursive"
	@echo "... mounts"
	@echo "... nsswitcher"
	@echo "... prepareEnvDir"
	@echo "... rebuild_cache"
	@echo "... src/linkRecursive.o"
	@echo "... src/linkRecursive.i"
	@echo "... src/linkRecursive.s"
	@echo "... src/mounts.o"
	@echo "... src/mounts.i"
	@echo "... src/mounts.s"
	@echo "... src/nsswitcher.o"
	@echo "... src/nsswitcher.i"
	@echo "... src/nsswitcher.s"
	@echo "... src/prepareEnvDir.o"
	@echo "... src/prepareEnvDir.i"
	@echo "... src/prepareEnvDir.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... src/utilsMount.o"
	@echo "... src/utilsMount.i"
	@echo "... src/utilsMount.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

